[language-server.deno-language-server]
command = "deno"
args = ["lsp"]
required-root-patterns = ["deno.json", "deno.jsonc"]

[language-server.wakatime]
command = "wakatime-ls"

[[language]]
name = "markdown"
language-servers = ["marksman", "wakatime"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "wakatime"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "nix"
language-servers = ["nil", "wakatime"]

# add as many entries as the number of the languages you use

[[language]]
name = "typescript"
file-types = ["ts"]
language-servers = ["deno-language-server", "wakatime"]

[[language]]
name = "javascript"
file-types = ["js"]
language-servers = ["deno-language-server", "wakatime"]

[[language]]
name = "tsx"
file-types = ["tsx"]
language-servers = ["typescript-language-server", "wakatime", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "wakatime", "tailwindcss-ls"]

[[language]]
name = "toml"
language-servers = ["taplo", "wakatime"]

[[language]]
name = "lua"
language-servers = ["lua-language-server", "wakatime"]

[[language]]
name = "python"
language-servers = ["pyright", "wakatime"]

[[language]]
name = "haskell"
language-servers = ["hls", "wakatime"]

[[language]]
name = "dockerfile"
language-servers = ["docker-langserver", "wakatime"]

# Additional common languages

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "wakatime", "tailwindcss-ls"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server", "wakatime"]

[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "wakatime"]

[[language]]
name = "bash"
language-servers = ["bash-language-server", "wakatime"]

[[language]]
name = "c"
language-servers = ["clangd", "wakatime"]

[[language]]
name = "go"
language-servers = ["gopls", "wakatime"]